# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages

r_packages:
  - drat
  - jrPackage

before_install: R -e 'source("https://install-github.me/r-lib/remotes")'
