# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages

# this is saying what R packages to install (from CRAN) on the CI runner
# i.e things that are needed as part of the building/testing/deploying
r_packages:
  - drat
