# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages

# this is saying what R packages to install (from CRAN) on the CI runner
# i.e things that are needed as part of the building/testing/deploying
r_packages:
  - drat

r_github_packages:
  - jumpingrivers/inteRgrate

script:
  - Rscript -e "inteRgrate::check_pkg()"
  - Rscript -e "inteRgrate::check_r_filenames()"
  - Rscript -e "inteRgrate::check_tidy_description()"
  - Rscript -e "inteRgrate::check_lintr()"
  - Rscript -e "inteRgrate::check_namespace()"

